### ISSUE TITLE
UI features 1.2

### ISSUE THREAD

**Issue by karbyshevds** [odahu/odahu-ui#12]
Tasks:
* [ ] [Sort on tables](https://git.epam.com/epmd-legn/legion-cicd/issues/139) - 3md
* [ ] ["Package button" in a training view](https://git.epam.com/epmd-legn/legion-cicd/issues/132) - 1md
* [ ] [Training(MLFlow) metrics](https://git.epam.com/epmd-legn/legion-cicd/issues/131) - 3md
* [ ] [ODAHU component versions view](https://git.epam.com/epmd-legn/legion-cicd/issues/130) - 1md
* [ ] [Unit tests](https://git.epam.com/epmd-legn/legion-cicd/issues/128) - 3 md
* [ ] [Default values from ODAHU config](https://git.epam.com/epmd-legn/legion-cicd/issues/94) - 1md
* [ ] [asterisks (*) for the mandatory fields](https://git.epam.com/epmd-legn/legion-cicd/issues/106) - 1md
* [ ] [Feedback tab](https://git.epam.com/epmd-legn/legion-cicd/issues/140) - 1 md
* [ ] [ODAHU entities from file](https://git.epam.com/epmd-legn/legion-cicd/issues/142) - 2md
* [ ] [Model REST endpoints tab](https://git.epam.com/epmd-legn/legion-cicd/issues/141) - 3md
* [ ] [Log out button](https://git.epam.com/epmd-legn/legion-cicd/issues/100) - 1 md

Sum: 20md

**Comment by alinaignatiuk** [comment]
Abandoned: https://github.com/odahu/odahu-ui/issues/16

**Comment by alinaignatiuk** [comment]
First need to be developed design (postponed for later releases): https://github.com/odahu/odahu-ui/issues/19, https://github.com/odahu/odahu-ui/issues/15
